language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install: "pip install -r requirements.txt && pip install -r test-requirements.txt"
script: "PYTHONPATH=$(pwd) python tests/tests_gerrit-connection.py && pylint gerrit"
