sudo: required
services:
  - docker
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get install -y haveged ldap-utils
  - sudo service haveged start
  - ./tests-setup.sh

language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install: "pip install -r requirements.txt && pip install -r test-requirements.txt"
script: "nosetests && pylint gerrit"
